----TABLES

DROP TABLE USERIN CASCADE CONSTRAINTS;

DROP TABLE PLAYLIST CASCADE CONSTRAINTS;

DROP TABLE SONG CASCADE CONSTRAINTS;

DROP TABLE ZEITPUNKT CASCADE CONSTRAINTS;

DROP TABLE SINGLEKUENSTLER CASCADE CONSTRAINTS;

DROP TABLE BANDKUENSTLER CASCADE CONSTRAINTS;

DROP TABLE SINGLEVEROEFFENTLICHT CASCADE CONSTRAINTS;

DROP TABLE BANDVEROEFFENTLICHT CASCADE CONSTRAINTS;

DROP TABLE FOLGT CASCADE CONSTRAINTS;

DROP TABLE HOERT CASCADE CONSTRAINTS;

----SEQUENCES

DROP SEQUENCE SEQ_SONGID;


----VIEWS

DROP VIEW UserIn_Land_Count CASCADE CONSTRAINTS;

DROP VIEW UserIn_Playlists CASCADE CONSTRAINTS;

DROP VIEW UserHistorie CASCADE CONSTRAINTS;

DROP VIEW ArtistSongs CASCADE CONSTRAINTS;

DROP VIEW BandSongs CASCADE CONSTRAINTS;

---PROCEDURE

DROP PROCEDURE INSERTFOLLOWER;





